server:
  port: 8080

spring:
  datasource:
    username: spring
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3307/my_e-commerce_website_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: my_e-commerce_website
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dokimlamut@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

vn_pay:
  tmn_code: ${VNP_TMN_CODE}
  secret_key: ${VNP_SECRET_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}